SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS student_answers;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS group_exams;
DROP TABLE IF EXISTS student_groups;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS exams;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS exam_incidents;

SET FOREIGN_KEY_CHECKS = 1;